### ISSUE TITLE
两个maven坐标没找到请核实

### ISSUE THREAD

**Issue by zhangyq1011** [ctripcorp/dal#1]
第一个maven坐标：
`<dependency>
            <groupId>com.microsoft.sqlserver</groupId>
            <artifactId>sqljdbc</artifactId>
            <version>${sqljdbc-version}</version>
        </dependency>
`
第二个mavne坐标：
` <dependency>
            <groupId>org.jasig.cas.client</groupId>
            <artifactId>cas-client-core-infosec-credis</artifactId>
            <version>${jasig-cas-version}</version>
        </dependency>
`
貌似maven中央库中没有、请核实。谢谢！！！

**Comment by wangyenan** [comment]
Hi，第一个jar可能在很多仓库中找不到，你需要在网上自己下载一份然后放到本地的仓库中去，第2个jar应该是我们内部使用的jar，不影响这个开源项目，你可以去掉这个dependency试试，之后我们会更新一下pom。再次感谢你的反馈。

**Comment by zhangyq1011** [comment]
注释掉没有问题、已经跑起来了。在查看原理从demo开始使用。
另外问一下：为何没有支持oracle？

**Comment by wangyenan** [comment]
因为携程内部没有用到oracle，所以并未测试过oracle是否可用，但我们都提供了基本的接口，如果有这方面的需求，用户可以自己实现类。

**Comment by zhangyq1011** [comment]
好的、多谢回复！先研究通原理再扩充oracle。
