### ISSUE TITLE
数据分片

### ISSUE THREAD

**Issue by hiddenzzh** [ctripcorp/dal#10]
数据分片之后需要将结果聚合返回，这个是在客户端实现的功能么? 还有比如要进行AVG的操作，是否会智能化为：再各个分库执行COUNT和TOTAL，然后进行AVG=(n*TOTAL)/(n*COUNT)的结果返回？

**Comment by lilongjiao** [comment]
如果要取得数据分片之后的聚合返回，可以在hint里加入merge操作，例如DalHints hints = new DalHints().mergeBy(new ResultMerger. IntAverage())，

具体可以查看dal-client中com.ctrip.platform.dal.dao里的ResultMerger

姓名：李龙姣
部门：R&D 框架 DAL
座位号：18#6F109
地址：金钟路968号凌空SOHO

发件人: hiddenzzh [mailto:notifications@github.com]
发送时间: 2016年10月10日 10:42
收件人: ctripcorp/dal <dal@noreply.github.com>
主题: [ctripcorp/dal] 数据分片 (#10)


数据分片之后需要将结果聚合返回，这个是在客户端实现的功能么? 还有比如要进行AVG的操作，是否会智能化为：再各个分库执行COUNT和TOTAL，然后进行AVG=(nTOTAL)/(nCOUNT)的结果返回？

**Comment by hiddenzzh** [comment]
THX

**Comment by hejiehui** [comment]
如果没有进一步的问题，请close issue
