### ISSUE TITLE
点击生成代码发生“Unable to create directory /app/dal_ftp/10000/java/Dao” 异常

### ISSUE THREAD

**Issue by codeyu** [ctripcorp/dal#12]
如题。操作系统为 OS X。

**Comment by wangyenan** [comment]
部署的server上，文件系统的权限问题，没有写入权限，请自己排查。

**Comment by gooree** [comment]
> 部署的server上，文件系统的权限问题，没有写入权限，请自己排查。

这个路径支持自定义配置吗？

**Comment by wangyenan** [comment]
支持的，classpath下conf.properties的第一个参数。
