### ISSUE TITLE
分片后，是否查询需要怎么处理吗？

### ISSUE THREAD

**Issue by itmifen** [ctripcorp/dal#19]
请问数据库分片处理后，数据库的查询需要做什么特殊的处理吗？？
在文档中没有看到这部分的说明。

**Comment by hejiehui** [comment]
需要保证查询的参数中包括可以用于分片计算的参数。dal会自动去参数对应分片查询，如果包含in参数，dal会自动划分in参数到多个分片，并聚合结果。
如果要查询的分片不与参数对应，或者希望去指定的分片，可以通过hints里面的inShard，inAllShards，inShards等方法指定

**Comment by hejiehui** [comment]
文档可以参考：https://github.com/ctripcorp/dal/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF-%E6%95%B0%E6%8D%AE%E5%BA%93%E5%88%86%E7%89%87
