### ISSUE TITLE
All-In-One Name是什么

### ISSUE THREAD

**Issue by slankka** [ctripcorp/dal#35]
![_20180602123455](https://user-images.githubusercontent.com/8142133/40870437-dbde2e6a-6661-11e8-83cc-0cc4590b2da9.png)
不写All-In-One Name无法添加 物理数据库。
All-In-One应该是个服务，是提供什么功能的Server？

**Comment by wangyenan** [comment]
是Dal.config中connection string的name，和Database.config中的name对应。
