### ISSUE TITLE
如何解决面向接口编程的问题

### ISSUE THREAD

**Issue by StephenHuge** [ctripcorp/dal#37]
项目中使用了接口来代替具体的类进行编程，很多Java实践中一般也会这么写，例如IOrderDao和OrderDao这种。

但现在框架生成的代码中我看会直接给一个OrderDao，不知道是没用对还是框架中没有提供这样的功能呢。在给出的Java Demo中好像也没有看到类似的代码。

这样如果为了贯彻面向接口编程的思路，可能就需要自己再写一个IOrderDao，OrderDao也需要改动代码了。

请问如何应对类似的问题呢？

**Comment by StephenHuge** [comment]
还有就是文档里的操作流程的界面好像和现在的操作界面相差比较大了，有空可以更新一下呀~

**Comment by death00** [comment]
直到现在，也确实是直接生成一个实体类，方法都是直接在这个实体类中，并没有生成接口。

**Comment by hejiehui** [comment]
不要为了接口编程而接口编程。面向接口编程的目的是为了随时切换实现逻辑。这个前提在DAL的应用中不存在，因为DAL本身的定位就是实现。
