### ISSUE TITLE
在初始化数据库的时候有问题 api_list 这个表

### ISSUE THREAD

**Issue by jordenLwq** [ctripcorp/dal#38]
解决办法：

CREATE TABLE `api_list` (
	`id` INT (11) NOT NULL AUTO_INCREMENT
	,`language` VARCHAR(45) NULL DEFAULT NULL
	,`db_type` VARCHAR(45) NULL DEFAULT NULL
	,`crud_type` VARCHAR(45) NULL DEFAULT NULL
	,`method_declaration` VARCHAR(200) NULL DEFAULT NULL
	,`method_description` TEXT NULL
	,`sp_type` VARCHAR(45) NULL DEFAULT NULL
	,PRIMARY KEY (`id`)
	) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

**Comment by wangyenan** [comment]
请问是什么问题？
