### ISSUE TITLE
Java客户端 事务处理问题

### ISSUE THREAD

**Issue by zhangyq1011** [ctripcorp/dal#4]
为何事务在DAO层处理呢？我们现在的SSI框架都是使用spring提供的声明式事务管理。DAL如何结合spring框架进行事务管理呢？好的框架和系统开源一般会拥抱类似spring等框架。在应该用系统开发中如何使用dal与其他系统结合？看demo都是直接使用dalclient进行调用的。谢谢，期待你的回复！

**Comment by zhangyq1011** [comment]
感谢你的热心回复。如果我们使用DAL应该如何做呢？完全抛弃Spring现在估计不太可能。把DAL做为独立的组件如何配合使用呢？有没有好的建议配合DI框架(Spring)的、再次感谢你。

**Comment by hejiehui** [comment]
使用DAL的transaction并不是要你抛弃spring。你可以继续使用spring。但就数据库事务这块，你可以不用spring的事务管理。
具体使用事务的方法我上面已经解释了。我不太理解你现在碰到什么问题。你可以加入qq群307228594，我们具体看看你的需求

**Comment by zhangyq1011** [comment]
好的。非常感谢！！！
