### ISSUE TITLE
maven 依赖找不到

### ISSUE THREAD

**Issue by GreedyPirate** [ctripcorp/dal#43]
```
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet</artifactId>
            <version>${javax.servlet-version}</version>
            <scope>provided</scope>
        </dependency>
```
编译dal-client时，如上依赖在maven中央仓库找不到，版本号为3.0.0.v201103241009，是携程内部版本吗

**Comment by wangyenan** [comment]
https://github.com/ctripcorp/dal/tree/master/doc/dependency

**Comment by GreedyPirate** [comment]
@wangyenan 找到了这个依赖，编译出来的dal-client是1.18.1版本，但是编译dao-gen-core却依赖dal-client的2.0.0版本，请确认下你们的模块依赖版本，应该以哪一个为准

**Comment by ctchentao** [comment]
dao-gen-core中用到的dal-client版本已经回退了，依赖dal-client是1.18.0版本，请以这个为准

**Comment by hejiehui** [comment]
如果版本发布的话，麻烦把release note的wiki和功能相关的wiki也更新一下，这样大家比较方便知道都提供了哪些功能

**Comment by GreedyPirate** [comment]
> dao-gen-core中用到的dal-client版本已经回退了，依赖dal-client是1.18.0版本，请以这个为准

如你所说，我更新了远程代码，dao-gen-core中dal-client版本改为了1.18.0，但是dal-client模块的版本是1.18.1, 所以依赖仍然找不到，希望你能在本地编译一次，编译成功后再发布代码，减少大家的部署成本

**Comment by ctchentao** [comment]
> > dao-gen-core中用到的dal-client版本已经回退了，依赖dal-client是1.18.0版本，请以这个为准
> 
> 如你所说，我更新了远程代码，dao-gen-core中dal-client版本改为了1.18.0，但是dal-client模块的版本是1.18.1, 所以依赖仍然找不到，希望你能在本地编译一次，编译成功后再发布代码，减少大家的部署成本

我们最近会发一个新版本，我们会规范下，感谢提醒

**Comment by cnodin** [comment]
拉下代码还是编译会报错哦。请问新版本啥时候出来呢？
