### ISSUE TITLE
Table 'ctrip.databaseSet' doesn't exist

### ISSUE THREAD

**Issue by anjingxz** [ctripcorp/dal#5]
你好，建表语句里面是databaseset，表名都是小写，但是后台报错
org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [SELECT id, name, provider, shardingStrategy, groupId, update_user_no, update_time FROM databaseSet WHERE name = ?]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'ctrip.databaseSet' doesn't exist
查询语句的表名（databaseSet）是大写，我的mysql数据库是区分大小写的，改成不区分大小写？

**Comment by wangyenan** [comment]
Hi，这个问题已经修复了，你是直接下载的war包还是通过源码编译生成的？

**Comment by anjingxz** [comment]
我通过源码生成的，但是刚刚换了个数据库又好了
