### ISSUE TITLE
咨询目前github上开源的DAL版本问题

### ISSUE THREAD

**Issue by mawenlong** [ctripcorp/dal#53]
DAL团队，您们好！
我想咨询下目前github上的DAL版本那几个是最新可用的；比如我看里面有cluster的相关版本。还有DAL目前咱们携程后续还会继续维护吗？
烦请告知，多谢携程的DAL团队

**Comment by hejiehui** [comment]
DAL目前还在维护，因为内部一直在使用，所以请不用担心。Cluster是配置相关的优化功能，文档应该还没更新出来。

**Comment by hejiehui** [comment]
另外目前还有DAL的衍生版本DAS可以选择：https://github.com/ppdaicorp/das
DAS跟DAL相比更加轻量级，可以参考：
https://segmentfault.com/a/1190000022640622
