### ISSUE TITLE
请问sharding之后能做排序吗

### ISSUE THREAD

**Issue by anjingxz** [ctripcorp/dal#6]
请问
queryAllByPage(1, 10, new DalHints().inAllShards().inTableShard(1))
能做排序吗，比如dal-demo例子里想按CountryId做排序

**Comment by hejiehui** [comment]
可以排序。自己传一个comparator
https://github.com/ctripcorp/dal/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF-Hints%E8%AF%B4%E6%98%8E#resultsorter
