### ISSUE TITLE
nullremote interface error 添加数据库管理提示错误

### ISSUE THREAD

**Issue by secondchilde** [ctripcorp/dal#64]
![image](https://user-images.githubusercontent.com/37492906/91919599-09951b00-ecf9-11ea-8747-7082210c72d0.png)
Dal 的大佬们 ,我在使用的时候 添加数据管理的时候报了这个问题nullremote interface error  能说下什么原因吗? 谢谢

**Comment by liuhuanjie** [comment]
开源版本代码生成器对DAL Cluster的支持不够完善，请使用Titan Key模式（流程中涉及DB Mode的选项全部选择Titan Key）
