### ISSUE TITLE
【linux 安裝編譯失敗】請更新POM文件 或包源

### ISSUE THREAD

**Issue by shan333chao** [ctripcorp/dal#7]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 07:11 min
[INFO] Finished at: 2016-09-30T04:06:07-04:00
[INFO] Final Memory: 11M/234M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project dao-gen-core: Could not resolve dependencies for project com.ctrip.platform:dao-gen-core:jar:1.0.5: Could not find artifact com.microsoft.sqlserver:sqljdbc:jar:4.0.2206 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by wangyenan** [comment]
请参考 https://github.com/ctripcorp/dal/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF-%E9%9B%86%E6%88%90%E8%AF%B4%E6%98%8E#microsoft-jdbc-drivers%E4%BE%9D%E8%B5%96%E5%AE%89%E8%A3%85

**Comment by shan333chao** [comment]
抽空又试了试，第一步dao-gen-core好了，编译通过
第二步dal-dao-gen又卡住了，详细信息如下
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 06:34 min
[INFO] Finished at: 2016-10-08T02:49:14-04:00
[INFO] Final Memory: 31M/305M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.8.1:jar (attach-javadocs) on project dal-dao-gen: MavenReportException: Error while creating archive:
[ERROR] Exit code: 1 - /root/Downloads/dal/dal-dao-gen/src/main/java/com/ctrip/platform/dal/daogen/resource/DalGroupDbResource.java:24: error: unknown tag: modified
[ERROR] * @modified yn.wang
[ERROR] ^
[ERROR] /root/Downloads/dal/dal-dao-gen/src/main/java/com/ctrip/platform/dal/daogen/resource/DalGroupDbSetResource.java:24: error: unknown tag: modified
[ERROR] * @modified yn.wang
[ERROR] ^
[ERROR] /root/Downloads/dal/dal-dao-gen/src/main/java/com/ctrip/platform/dal/daogen/resource/DalGroupMemberResource.java:24: error: unknown tag: modified
[ERROR] * @modified yn.wang
[ERROR] ^
[ERROR] /root/Downloads/dal/dal-dao-gen/src/main/java/com/ctrip/platform/dal/daogen/resource/DalGroupProjectResource.java:19: error: bad HTML entity
[ERROR] * DAL Project & Code 一览
[ERROR] ^
[ERROR] /root/Downloads/dal/dal-dao-gen/src/main/java/com/ctrip/platform/dal/daogen/resource/GenTaskByFreeSqlResource.java:29: error: unknown tag: modified
[ERROR] * @modified yn.wang
[ERROR] ^
[ERROR] /root/Downloads/dal/dal-dao-gen/src/main/java/com/ctrip/platform/dal/daogen/resource/GenTaskBySqlBuilderResource.java:35: error: unknown tag: modified
[ERROR] * @modified yn.wang
[ERROR] ^
[ERROR] /root/Downloads/dal/dal-dao-gen/src/main/java/com/ctrip/platform/dal/daogen/resource/GenTaskByTableViewResource.java:26: error: unknown tag: modified
[ERROR] * @modified yn.wang
[ERROR] ^
[ERROR] /root/Downloads/dal/dal-dao-gen/src/main/java/com/ctrip/platform/dal/daogen/resource/ProjectResource.java:367: warning: no description for @param
[ERROR] * @param project_id
[ERROR] ^
[ERROR] /root/Downloads/dal/dal-dao-gen/src/main/java/com/ctrip/platform/dal/daogen/resource/ProjectResource.java:368: warning: no description for @return
[ERROR] * @return
[ERROR] ^
[ERROR] 
[ERROR] Command line was: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.102-1.b14.el7_2.x86_64/jre/../bin/javadoc @options @packages
[ERROR] 
[ERROR] Refer to the generated Javadoc files in '/root/Downloads/dal/dal-dao-gen/target/apidocs' dir.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by wangyenan** [comment]
请使用java7重新编译一下。

**Comment by shan333chao** [comment]
编译通过 成功运行，感谢感谢！
