### ISSUE TITLE
mysql表名需要忽略大小写？

### ISSUE THREAD

**Issue by pengliaoye** [ctripcorp/dal#8]
StatementCallback; bad SQL grammar [select en.id, en.name, en.databaseType, en.sharding, en.connectionString, en.databaseSet_Id, en.update_user_no, en.update_time from databasesetentry as en join databaseSet as se on en.databaseSet_Id = se.id where se.name = 'meipinset' and en.databaseType = 'Master' limit 1;]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'dal.databaseSet' doesn't exist

databaseset这个表在数据库全是小写的

**Comment by wangyenan** [comment]
Hi，这个问题已经修复，重新pull一下代码并打包就行了。
