### ISSUE TITLE
我想扩展支持Oracle，请问如何做？

### ISSUE THREAD

**Issue by doterme** [ctripcorp/dal#9]
公司的数据库主要是Oracle，想把Dal的C# Client扩展一下来支持Oracle，请问怎么做？有文档么？

**Comment by wangyenan** [comment]
抱歉，暂时还没有任何Oracle相关的文档，如果要支持Oracle，可以参考MySqlProvider这个项目的实现方法，主项目Arch.Data反射加载OracleProvider，然后OracleProvider去引用Oracle提供的.Net驱动，实现我们定义的IDatabaseProvider接口即可。
